services:
  db:
    image: mysql:8.0.36
    container_name: ${DATABASE_HOST}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - app

  server:
    build:
      context: ./
      dockerfile: app.dev.Dockerfile
    container_name: nest-server
    restart: always
    volumes:
      - appdata:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh ${DATABASE_HOST}:${DATABASE_PORT} -t 15
        /wait-for-it.sh ${REDIS_HOST}:${REDIS_PORT} -t 15
        yarn start_app:dev
    env_file:
      - .env
    networks:
      - app

  redis:
    image: redis:7.0
    container_name: ${REDIS_HOST}
    command: [
      "redis-server",
      "--port ${REDIS_PORT:-6379}",
      "--appendonly yes",
      "--appendfilename appendonly.aof",
      "--dbfilename dump.rdb"
    ]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
  redisdata:
    driver: local
